### ISSUE TITLE
Comment widget: line breaks are lost in read-only mode

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-client-core#100]
Should really just be a matter of adding:

```css
.r6o-readonly-comment { white-space: pre; }
```
